title: RICHPIN의 블로그
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: RICHPIN # add your name
author-img: github_profile(smaller).jpeg # add your photo
about-author: Junior Developer # add description
social-instagram: nothinbutperson
social-github: richpin # add your Github handle
social-email: richpinkr99@gmail.com # add your Email address

# Disqus
discus-identifier: richpin # add your discus identifier

# Tracker
analytics: # Google Analytics
  provider: "ggogle-gtag"
  
  google:
    tracking_id: "G-KY1Q68TEJ5"
    anonymize_ip : # true, false(default)

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
